# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
  modulesPath,
***REMOVED***
***REMOVED***: ***REMOVED***
***REMOVED***
    (modulesPath + "/profiles/qemu-guest.nix")
***REMOVED***

  boot.initrd.availableKernelModules = ["uhci_hcd" "ehci_pci" "ahci" "virtio_pci" "sr_mod" "virtio_blk"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = ***REMOVED***
    device = "/dev/disk/by-uuid/b44df0dd-174f-47b0-af88-fd66c6e7deb5";
    fsType = "ext4";
***REMOVED***

  fileSystems."/boot" = ***REMOVED***
    device = "/dev/disk/by-uuid/5564-A778";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
***REMOVED***

  swapDevices = [];

***REMOVED*** Enables DHCP on each ethernet and wireless interface. In case of scripted networking
***REMOVED*** (the default) this is the recommended approach. When using systemd-networkd it's
***REMOVED*** still possible to use this option, but it's recommended to use it in conjunction
***REMOVED*** with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
***REMOVED*** networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
***REMOVED***
