:set tabstop=4
:set shiftwidth=4
:set expandtab

set laststatus=2
set term=xterm
set viminfo+=n~/.config/vim/viminfo
set noshowmode

" Enable mouse support
:set mouse=a

" Set path for plugins/packages
:set packpath+=$XDG_CONFIG_HOME/vim/packages

if !has('gui_running')
  set t_Co=256
endif
