name: "Clear disk space"
description: "Frees disk space in the GHA runner"
inputs:
  debug:
    description: Enabling this will print before and after disk sizes
    default: 'false'
    required: false

runs:
  using: "composite"
  steps:
    - name: Get disk usage
      shell: bash
      run: |
        df -h

    - name: Detailed usage
      if: inputs.debug == 'true'
      shell: bash
      run: |
        du -h -d5 / 2>/dev/null | sort -hr | head -n 20 || true

    - name: Clear
      shell: bash
      run: |
        ${{ github.action_path }}/clean.sh
        sudo docker system prune -af || true
        sudo docker image prune -af || true
        sudo docker builder prune -af || true

    - name: Get disk usage
      shell: bash
      run: |
        df -h

    - name: Detailed usage
      if: inputs.debug == 'true'
      shell: bash
      run: |
        du -h -d5 / 2>/dev/null | sort -hr | head -n 20 || true
