;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█░░░█░█░█▀█░█░█░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░█░█░░░░█░░█▀▀░█▀█░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░░▀░░▀░░░▀░▀░▀▀▀│
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[glyph]
gleft = 
gright = 

[module/left1]
type = custom/text
content-background = $***REMOVED***color.shade2***REMOVED***
content-foreground = $***REMOVED***color.shade1***REMOVED***
content = $***REMOVED***glyph.gleft***REMOVED***
content-font = 2

[module/left2]
type = custom/text
content-background = $***REMOVED***color.background***REMOVED***
content-foreground = $***REMOVED***color.shade2***REMOVED***
content = $***REMOVED***glyph.gleft***REMOVED***
content-font = 2

# ==================================

[module/right1]
type = custom/text
content-background = $***REMOVED***color.shade2***REMOVED***
content-foreground = $***REMOVED***color.shade1***REMOVED***
content = $***REMOVED***glyph.gright***REMOVED***
content-font = 2

[module/right2]
type = custom/text
content-background = $***REMOVED***color.shade3***REMOVED***
content-foreground = $***REMOVED***color.shade2***REMOVED***
content = $***REMOVED***glyph.gright***REMOVED***
content-font = 2

[module/right3]
type = custom/text
content-background = $***REMOVED***color.shade4***REMOVED***
content-foreground = $***REMOVED***color.shade3***REMOVED***
content = $***REMOVED***glyph.gright***REMOVED***
content-font = 2

[module/right4]
type = custom/text
content-background = $***REMOVED***color.shade5***REMOVED***
content-foreground = $***REMOVED***color.shade4***REMOVED***
content = $***REMOVED***glyph.gright***REMOVED***
content-font = 2

[module/right5]
type = custom/text
content-background = $***REMOVED***color.shade6***REMOVED***
content-foreground = $***REMOVED***color.shade5***REMOVED***
content = $***REMOVED***glyph.gright***REMOVED***
content-font = 2

[module/right6]
type = custom/text
content-background = $***REMOVED***color.shade7***REMOVED***
content-foreground = $***REMOVED***color.shade6***REMOVED***
content = $***REMOVED***glyph.gright***REMOVED***
content-font = 2

[module/right7]
type = custom/text
content-background = $***REMOVED***color.background***REMOVED***
content-foreground = $***REMOVED***color.shade7***REMOVED***
content = $***REMOVED***glyph.gright***REMOVED***
content-font = 2

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
