# Start XDG autostart .desktop files using dex. See also
exec --no-startup-id dex-autostart --autostart --environment i3

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
exec --no-startup-id nm-applet

# Compositor
exec --no-startup-id picom --config $XDG_CONFIG_HOME/picom.conf

# Wallpaper
exec --no-startup-id feh --bg-fill --no-fehbg ~/Pictures/Wallpapers/wallpaper.png

# Status Bar
exec_always --no-startup-id $XDG_CONFIG_HOME/polybar/launch.sh --shades &

# Keyring
exec --no-startup-id dbus-update-activation-environment --all
exec --no-startup-id gnome-keyring-daemon --start --components=secrets,ssh

# OpenRazer
exec --no-startup-id openrazer-daemon -r

