bar {
	status_command i3status
	mode hide
	position top
	colors {
		background #242424
	}
}

# Start XDG autostart .desktop files using dex. See also
#exec --no-startup-id dex-autostart --autostart --environment i3

# Status Bar
#exec_always --no-startup-id $XDG_CONFIG_HOME/polybar/launch.sh --shades

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
#exec --no-startup-id nm-applet

# Compositor
exec --no-startup-id picom --config $XDG_CONFIG_HOME/picom.conf --experimental-backends -b

# Wallpaper
exec --no-startup-id feh --bg-scale --no-xinerama ~/Pictures/Wallpaper/Dual.png
