[language-server]
clangd = { command = "clangd", args = ["--header-insertion=never"]}
biome = { command = "biome", args = ["lsp-proxy"] }
fish_lsp = {command = "fish-lsp", args = ["start"]}
slangd = {command = "slangd"}
gpt = {command = "helix-gpt", args = ["--handler", "copilot"]}

[[language]]
name = "fish"
scope = "source.fish"
auto-format = true
language-servers = [{ name = "fish_lsp" }]

[[language]]
name = "meson"
scope = "source.meson"
injection-regex = "meson"
#file-types = [{ glob = "meson.build" }, { glob = "meson_options.txt" }]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
auto-format = true
formatter = {command = "muon", args = ["fmt", "-"]}

[[language]]
name = "nix"
scope = "source.nix"
#file-types = ["nix"]
auto-format = true
formatter = { command = "alejandra", args = ["-q"] }

[[language]]
name = "cpp"
language-servers = [
  "clangd",
  "gpt"
]

[[language]]
name = "python"
language-servers = [
  "ruff",
  "basedpyright",
  "gpt",
]

[[language]]
name = "objc"
scope = "source.objc"
file-types = ["m", "mm", "M"]
injection-regex = "objc"
roots = ["xcodeproj"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
language-servers = [ {name = "clangd"} ]

[[grammar]]
name = "objc"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-objc", rev = "18802acf31d0b5c1c1d50bdbc9eb0e1636cab9ed" }


[[language]]
name = "slang"
scope = "source.slang"
file-types = ["slang"]
auto-format = true
language-servers = [{name = "slangd"}]
comment-token = "//"

[[grammar]]
name = "slang"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-slang", rev = "3ed23c04a412a0559162d9cadf96dfff7cb36079" }

##################
### BiomeJS Setup
##################

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true
formatter = { command = "biome", args = ["format", "--stdin-file-path", "a.js"] }

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true
formatter = { command = "biome", args = ["format", "--stdin-file-path", "a.ts"] }

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "a.tsx"] }

[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "a.jsx"] }

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]
