#!/usr/bin/bash
#
#   checkupdates: Safely print a list of pending updates.
#
#   Copyright (c) 2013 Kyle Keen <keenerd@gmail.com>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

declare -r myname='checkupdates'
declare -r myver='1.0.0'

plain() ***REMOVED***
	(( QUIET )) && return
	local mesg=$1; shift
	printf "$***REMOVED***BOLD***REMOVED***    $***REMOVED***mesg***REMOVED***$***REMOVED***ALL_OFF***REMOVED***\n" "$@" >&1
***REMOVED***

msg() ***REMOVED***
	(( QUIET )) && return
	local mesg=$1; shift
	printf "$***REMOVED***GREEN***REMOVED***==>$***REMOVED***ALL_OFF***REMOVED***$***REMOVED***BOLD***REMOVED*** $***REMOVED***mesg***REMOVED***$***REMOVED***ALL_OFF***REMOVED***\n" "$@" >&1
***REMOVED***

msg2() ***REMOVED***
	(( QUIET )) && return
	local mesg=$1; shift
	printf "$***REMOVED***BLUE***REMOVED***  ->$***REMOVED***ALL_OFF***REMOVED***$***REMOVED***BOLD***REMOVED*** $***REMOVED***mesg***REMOVED***$***REMOVED***ALL_OFF***REMOVED***\n" "$@" >&1
***REMOVED***

ask() ***REMOVED***
	local mesg=$1; shift
	printf "$***REMOVED***BLUE***REMOVED***::$***REMOVED***ALL_OFF***REMOVED***$***REMOVED***BOLD***REMOVED*** $***REMOVED***mesg***REMOVED***$***REMOVED***ALL_OFF***REMOVED***" "$@" >&1
***REMOVED***

warning() ***REMOVED***
	local mesg=$1; shift
	printf "$***REMOVED***YELLOW***REMOVED***==> $(gettext "WARNING:")$***REMOVED***ALL_OFF***REMOVED***$***REMOVED***BOLD***REMOVED*** $***REMOVED***mesg***REMOVED***$***REMOVED***ALL_OFF***REMOVED***\n" "$@" >&2
***REMOVED***

error() ***REMOVED***
	local mesg=$1; shift
	printf "$***REMOVED***RED***REMOVED***==> $(gettext "ERROR:")$***REMOVED***ALL_OFF***REMOVED***$***REMOVED***BOLD***REMOVED*** $***REMOVED***mesg***REMOVED***$***REMOVED***ALL_OFF***REMOVED***\n" "$@" >&2
***REMOVED***

# check if messages are to be printed using color
unset ALL_OFF BOLD BLUE GREEN RED YELLOW
if [[ -t 2 && ! $USE_COLOR = "n" ]]; then
	# prefer terminal safe colored and bold text when tput is supported
	if tput setaf 0 &>/dev/null; then
		ALL_OFF="$(tput sgr0)"
		BOLD="$(tput bold)"
		BLUE="$***REMOVED***BOLD***REMOVED***$(tput setaf 4)"
		GREEN="$***REMOVED***BOLD***REMOVED***$(tput setaf 2)"
		RED="$***REMOVED***BOLD***REMOVED***$(tput setaf 1)"
		YELLOW="$***REMOVED***BOLD***REMOVED***$(tput setaf 3)"
	else
		ALL_OFF="\e[1;0m"
		BOLD="\e[1;1m"
		BLUE="$***REMOVED***BOLD***REMOVED***\e[1;34m"
		GREEN="$***REMOVED***BOLD***REMOVED***\e[1;32m"
		RED="$***REMOVED***BOLD***REMOVED***\e[1;31m"
		YELLOW="$***REMOVED***BOLD***REMOVED***\e[1;33m"
	fi
fi
readonly ALL_OFF BOLD BLUE GREEN RED YELLOW


if (( $# > 0 )); then
	echo "$***REMOVED***myname***REMOVED*** v$***REMOVED***myver***REMOVED***"
	echo
	echo "Safely print a list of pending updates"
	echo
	echo "Usage: $***REMOVED***myname***REMOVED***"
	echo
	echo 'Note: Export the "CHECKUPDATES_DB" variable to change the path of the temporary database.'
	exit 0
fi

if ! type -P fakeroot >/dev/null; then
	error 'Cannot find the fakeroot binary.'
	exit 1
fi

if [[ -z $CHECKUPDATES_DB ]]; then
	CHECKUPDATES_DB="$***REMOVED***TMPDIR:-/tmp***REMOVED***/checkup-db-$***REMOVED***USER***REMOVED***/"
fi

trap 'rm -f $CHECKUPDATES_DB/db.lck' INT TERM EXIT

DBPath="$(pacman-conf DBPath)"
if [[ -z "$DBPath" ]] || [[ ! -d "$DBPath" ]]; then
	DBPath="/var/lib/pacman/"
fi

mkdir -p "$CHECKUPDATES_DB"
ln -s "$***REMOVED***DBPath***REMOVED***/local" "$CHECKUPDATES_DB" &> /dev/null
if ! fakeroot -- pacman -Sy --dbpath "$CHECKUPDATES_DB" --logfile /dev/null &> /dev/null; then
       error 'Cannot fetch updates'
       exit 1
fi
pacman -Qu --dbpath "$CHECKUPDATES_DB" 2> /dev/null | grep -v '\[.*\]'

exit 0

# vim: set noet:
