import = [
    "~/.config/alacritty/themes/_active.toml"
]

[font]
size = 9.5

[font.normal]
family = "JetBrainsMono Nerd Font"

[keyboard]
bindings = [
  ***REMOVED*** key = "N", mods = "Control|Shift", action = "CreateNewWindow" ***REMOVED***
]
