import = [
    "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
]

[font]
size = 9.5

[keyboard]
bindings = [
  ***REMOVED*** key = "N", mods = "Control|Shift", action = "CreateNewWindow" ***REMOVED***
]
