[[language]]
name = "meson"
scope = "source.meson"
formatter = ***REMOVED***command = "muon", args = ["fmt", "-"]***REMOVED***
file-types = ["meson.build", "meson_options.txt"]

##################
### BiomeJS Setup
##################

[language-server]
biome = ***REMOVED*** command = "biome", args = ["lsp-proxy"] ***REMOVED***

[[language]]
name = "javascript"
language-servers = [ ***REMOVED*** name = "typescript-language-server", except-features = [ "format" ] ***REMOVED***, "biome" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ "biome", ***REMOVED*** name = "typescript-language-server", except-features = [ "format" ] ***REMOVED*** ]
auto-format = true
