[language-server]
biome = ***REMOVED*** command = "biome", args = ["lsp-proxy"] ***REMOVED***
clangd = ***REMOVED*** command = "clangd", args = ["--header-insertion=never"]***REMOVED***

[[language]]
name = "meson"
scope = "source.meson"
injection-regex = "meson"
#file-types = [***REMOVED*** glob = "meson.build" ***REMOVED***, ***REMOVED*** glob = "meson_options.txt" ***REMOVED***]
comment-token = "#"
indent = ***REMOVED*** tab-width = 2, unit = "  " ***REMOVED***
auto-format = true
formatter = ***REMOVED***command = "muon", args = ["fmt", "-"]***REMOVED***

[[language]]
name = "nix"
scope = "source.nix"
#file-types = ["nix"]
auto-format = true
formatter = ***REMOVED*** command = "alejandra", args = ["-q"] ***REMOVED***

##################
### BiomeJS Setup
##################

[[language]]
name = "javascript"
language-servers = [ ***REMOVED*** name = "typescript-language-server", except-features = [ "format" ] ***REMOVED***, "biome" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ ***REMOVED*** name = "typescript-language-server", except-features = [ "format" ] ***REMOVED***, "biome" ]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [ ***REMOVED*** name = "typescript-language-server", except-features = [ "format" ] ***REMOVED***, "biome" ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ ***REMOVED*** name = "typescript-language-server", except-features = [ "format" ] ***REMOVED***, "biome" ]

[[language]]
name = "json"
language-servers = [ ***REMOVED*** name = "vscode-json-language-server", except-features = [ "format" ] ***REMOVED***, "biome" ]
