[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }
clangd = { command = "clangd", args = ["--header-insertion=never"]}

[[language]]
name = "meson"
scope = "source.meson"
injection-regex = "meson"
#file-types = [{ glob = "meson.build" }, { glob = "meson_options.txt" }]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
auto-format = true
formatter = {command = "muon", args = ["fmt", "-"]}

[[language]]
name = "nix"
scope = "source.nix"
#file-types = ["nix"]
auto-format = true
formatter = { command = "alejandra", args = ["-q"] }

##################
### BiomeJS Setup
##################

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]
