name: Update flake.lock

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -sSf -L https://install.lix.systems/lix | sh -s -- install
      - uses: DeterminateSystems/update-flake-lock@v24  
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated
          token: ${{ secrets.FLAKE_PR_TOKEN }}
          path-to-flake-dir: dot_config/flake/
