name: Update flake.lock

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 5' # runs weekly on Sunday at 00:00

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install nix
        uses: DeterminateSystems/determinate-nix-action@v3.5.2
        with:
          extra-conf: "lazy-trees = true"

      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false

      - uses: DeterminateSystems/update-flake-lock@v24  
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated
          token: ${{ secrets.FLAKE_PR_TOKEN }}
          path-to-flake-dir: dot_config/flake/
