on:
  push:

jobs:
  build:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macOS-latest]
  #       host: [wash, mal, hinge]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v16

    - run: |
        nix build dot_config/flake#nixosConfigurations.wash.config.system.build.toplevel
