on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Maximize build space
      shell: bash
      run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a
          df -h
    - uses: actions/checkout@v4
    - uses: samueldr/lix-gha-installer-action@v2025-02-26.prerelease

    - uses: cachix/cachix-action@v16
      with:
        name: tmayoff
        authToken: '${{ secrets.CACHIX_AUTH }}'
    - run: |
        nix build ./dot_config/flake#nixosConfigurations.wash.config.system.build.toplevel --cores 1 -j1
        
