on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        host: [wash, mal, hinge]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v16

    - run: |
        cd dot_config/flake
        sudo nixos-rebuild switch --flake ~/.config/flake#${{ matrix.host }}
