on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            hostname: wash
            arch: x86_64-linux
          - os: macos-latest
            hostname: MAC-C57KK2TC69
            arch: aarch64-darwin

    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
    - name: Maximize build space
      if: runner.os == 'Linux'
      uses: ./.github/actions/disk_space

    - uses: actions/checkout@v4

    - name: install nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        source-url: "${{ format('https://install.lix.systems/lix/lix-installer-{0}', matrix.arch) }}"
        diagnostic-endpoint: ""
        backtrace: "true"

    - uses: cachix/cachix-action@v16
      with:
        name: tmayoff
        authToken: '${{ secrets.CACHIX_AUTH }}'

    - uses: workflow/nix-shell-action@v3
      if: runner.os == 'Linux'
      name: build nixos
      with:
        packages: nh
        script: |
          nh os build ./dot_config/flake#nixosConfigurations.${{matrix.hostname}} --no-nom -- --cores 1 -j1

    - uses: workflow/nix-shell-action@v3
      if: runner.os == 'macOS'
      name: build darwin
      with:
        packages: nh
        script: |
          nh darwin build ./dot_config/flake#darwinConfigurations.${{matrix.hostname}} --no-nom -- --cores 1 -j1 
