on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            hostname: wash
          - os: macos-latest
            hostname: MAC-C57KK2TC69

    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
    - name: Maximize build space
      if: runner.os == 'Linux'
      shell: bash
      run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a
          df -h
    - uses: actions/checkout@v4
    - uses: samueldr/lix-gha-installer-action@v2025-02-26.prerelease

    - uses: cachix/cachix-action@v16
      with:
        name: tmayoff
        authToken: '${{ secrets.CACHIX_AUTH }}'

    - uses: workflow/nix-shell-action@v3
      if: runner.os == 'Linux'
      name: build nixos
      with:
        packages: nh
        script: |
          nh os build ./dot_config/flake#nixosConfigurations.${{matrix.hostname}} --no-nom -- --cores 1 -j1

    - uses: workflow/nix-shell-action@v3
      if: runner.os == 'macOS'
      name: build darwin
      with:
        packages: nh
        script: |
          nh darwin build ./dot_config/flake#darwinConfigurations.${{matrix.hostname}} --no-nom -- --cores 1 -j1 
