on:
  push:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            hostname: wash
          - os: macos-latest
            hostname: MAC-C57KK2TC69

    runs-on: ${{ matrix.os }}

    steps:
    - name: Maximize build space
      if: runner.os == 'Linux'
      shell: bash
      run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a
          df -h
    - uses: actions/checkout@v4
    - uses: samueldr/lix-gha-installer-action@v2025-02-26.prerelease

    - uses: cachix/cachix-action@v16
      with:
        name: tmayoff
        authToken: '${{ secrets.CACHIX_AUTH }}'

    - name: build nixos
      if: runner.os == 'Linux'
      run: |
        nh os build ./dot_config/flake/ -- --cores 1 -j1

    - name: build darwin
      if: runner.os == 'macOS'
      run: |
        nh darwin build ./dot_config/flake/ -- --cores 1 -j1 
